Add news to LPB
department-of-veterans-affairs/lighthouse-platform-backend pull request #255
Opened 2023-02-13 14:57 UTC by andresriveratoro

2023-02-13 19:46 UTC, gileswells requested changes
Good first pass but I think we can get in some additional improvements while we're kinda holding for webpack / nodejs updates prior to IA work.

2023-02-13 19:46 UTC, gileswells commented on db/migrate/20230213145053_create_news.rb
> +
Don't you need a `source` column as well?

2023-02-13 19:46 UTC, gileswells commented on app/models/news.rb
> +  }.freeze
The ticket calls out adding news and categories to the database. To me, I would much prefer to see the categories added as a related table with fields that cover the config and on page text shows in the developer portal that is currently coming from [this file](https://github.com/department-of-veterans-affairs/developer-portal/blob/master/src/content/news.yml).

2023-02-22 22:24 UTC, closed without merging

2023-02-22 22:24 UTC, andresriveratoro commented
Closing in favor of https://github.com/department-of-veterans-affairs/lighthouse-platform-backend/pull/259