[API-27989] - Enhance Security Alert GHA Workflow
department-of-veterans-affairs/lighthouse-platform-backend pull request #301
Opened 2023-07-19 18:21 UTC by jw81

Original Issue :: [API-27989](https://jira.devops.va.gov/browse/API-27989)

- Adds logic to check for open Dependabot alerts
- Adds logic to check for open Secret Scanning alerts
- Adds logic to send a message to the `#team-okapi` Lighthouse Slack channel if an open alert is found

2023-07-19 19:51 UTC, gileswells requested changes
Consider changing the channel target.

2023-07-19 19:51 UTC, gileswells commented on .github/workflows/notify-security-alerts.yml
> +          channel-id: C01931CFMTQ
I feel like we should create a #team-okapi-alerts channel rather than shoot this into our default channel. If there is something that we're seeing come up and it takes us a few days to actually be able to get to it we're going to have this post multiple times. Might make it a bit cluttered in a channel for collaboration.

2023-07-19 20:50 UTC, jw81 commented on .github/workflows/notify-security-alerts.yml
> +          channel-id: C01931CFMTQ
Ah, I did that because it was requested that all teams set this up to report to their respective `#team-X` channels in Lighthouse Slack.  

> _In further support of this ask, please set up a Slack alert which reports these to your #team- channel for all of your GitHub repositories._

[Reference](https://lighthouseva.slack.com/archives/CAZF880HW/p1689004091121079)

2023-07-20 16:28 UTC, gileswells commented on .github/workflows/notify-security-alerts.yml
> +          channel-id: C01931CFMTQ
I get that but I still think that `#team-okapi-alerts` is a fair way to do it especially if we make note in our main channel the presence of the second channel and cross reference an alert if it's something that's going to require a larger effort.

Like, if we manage it well, it should be fine. I'd prefer to go with an alerts channel but if they give push back then we can move it. More a preference but I know that this is going to be to satisfy an external requirement so it's more so up to them.

2023-07-20 16:33 UTC, jw81 commented on .github/workflows/notify-security-alerts.yml
> +          channel-id: C01931CFMTQ
Fair enough.  We can try spinning up an alerts channel and sending the alerts there.  We can always point it back to our main channel if they really insist upon that.

2023-07-20 16:41 UTC, jw81 commented on .github/workflows/notify-security-alerts.yml
> +          channel-id: C01931CFMTQ
Created the new `#team-okapi-alerts` Slack channel and changed the workflow to send to that new channel.

2023-07-20 17:37 UTC, gileswells approved these changes

2023-07-21 16:11 UTC, merged