[API-31636] - Support test user data deeplink
department-of-veterans-affairs/lighthouse-platform-backend pull request #323
Opened 2023-12-12 14:55 UTC by gileswells

https://jira.devops.va.gov/browse/API-31636

This endpoint validates the request for test user data and then fetches it from s3 and provides it to the user.

2023-12-12 19:17 UTC, gileswells commented on app/api/v0/consumers.rb
> +          deeplink_hash = generate_deeplink_hash(user)
I have this here for debugging purposes. Based on a flipper setting we can turn it on in dev where the sandbox form will return the hash so we can inspect the network traffic and validate the deeplink is working without turning on emails sending out from signups to dev.

2023-12-12 19:51 UTC, jw81 commented on app/api/v0/consumers.rb
> +          deeplink_hash = generate_deeplink_hash(user)
Ahhhhhh, nvm.
I totally missed line#172 where you're referencing the `deeplink_hash` var.  
Ignore me.

2023-12-14 17:20 UTC, jw81 commented on app/api/v0/consumers.rb
> +          deeplink_url = generate_deeplink(url_slug, user)
I think there might be a hiccup here.

I was running this locally and it looks like the `user` isn't yet saved at this point.  Meaning that when it gets into `generate_deeplink()`, the `user.id` is going to be `nil`.

I'm not sure exactly "why" it was setup this way, but it looks like the `User` is not saved until OKTA has had a chance to create the application. [REF](https://github.com/department-of-veterans-affairs/lighthouse-platform-backend/blob/master/app/services/okta/base_service.rb#L81)

Maybe the fix is just simply calling `user.save!` before hitting your new logic?  (trying to think through if there's any drawbacks/concerns of doing that 🤔 )

2023-12-18 17:54 UTC, jw81 requested changes
Pointed out a slight hiccup that I think we'll need to account for.  Hopefully should be an easy fix.

2024-01-05 20:09 UTC, andresriveratoro approved these changes
LGTM

2024-01-05 20:14 UTC, gileswells commented on app/api/v0/consumers.rb
> +          deeplink_url = generate_deeplink(url_slug, user)
I was resistant to this change but I realized that the user, on their first ever signup, would be nil at this point because they don't already exist like my test user does in my local. 🤦‍♂️ I've added the user.save! above inside this conditional so it'll only fire if we need the user.id at this point.

2024-01-05 22:16 UTC, andresriveratoro approved these changes

2024-01-05 22:16 UTC, gileswells commented on spec/spec_helper.rb
> +  SimpleCov.minimum_coverage_by_file 85
Ticket to re-raise the minimum coverage level
https://jira.devops.va.gov/browse/API-32847

2024-01-05 22:17 UTC, merged

2024-01-06 02:10 UTC, jw81 commented on app/api/v0/consumers.rb
> +          deeplink_url = generate_deeplink(url_slug, user)
I think it's prob fine like this, but I don't think the "user.save!" is necessary here because the 2 calls to ".consumer_signup()" up above would have already called "user.save!" before this.