[API-33897] - Delete utilities and promote to prod code
department-of-veterans-affairs/lighthouse-platform-backend pull request #340
Opened 2024-02-20 19:42 UTC by gileswells

https://jira.devops.va.gov/browse/API-33897

Remove utilities routes and all legacy code related to the now abandoned promote to prod initiative that previously existed.

2024-02-20 22:38 UTC, jw81 commented on app/api/v0/consumers.rb
> +        # header 'Access-Control-Allow-Origin', request.host_with_port
Probably want to bring this back for now, right?

2024-02-20 22:41 UTC, jw81 commented on app/api/v0/consumers.rb
> +          response = s3.get_object(bucket:, key:)
Was this a pattern you saw and really liked?  Or did Rubocop or something call it out?
I'm not opposed to the changes btw.  Just curious how ya came about it.    😄

2024-02-20 22:50 UTC, jw81 commented on lib/tasks/utilities.rake
> +      puts users
I'm not sure we want to be printing out the list of `users` because anything we print is going to be revealed in logs.

2024-02-20 22:53 UTC, jw81 requested changes
Threw a couple comments on there.  For one of them, I think we'll definitely have to remove some logic because it relies on printing to console and that data would likely be flagged as PII.

2024-02-21 16:41 UTC, gileswells commented on app/api/v0/consumers.rb
> +          response = s3.get_object(bucket:, key:)
Just Rubocop yelling at us in the builds. They were all automatically correctable so it still "passed" the builds but it was ugly.

2024-02-21 20:30 UTC, gileswells commented on app/api/v0/providers.rb
> -                            kong_consumer: kong_consumer,
Checked and there isn't any usage on these endpoints. Deleted.

2024-02-26 15:46 UTC, jw81 approved these changes
LGTM 👍 

We'll wanna make sure to do some decent functional testing in the lower environments to make sure everything is still working as expected once this is merged in.

2024-02-26 18:40 UTC, merged