[API-35047] - Integrate with lighthouse auth for app creation
department-of-veterans-affairs/lighthouse-platform-backend pull request #360
Opened 2024-05-01 21:46 UTC by jw81

Original Issue :: [API-35047](https://jira.devops.va.gov/browse/API-35047)

- Adds ability for LPB to make OAuth app creation requests via the Lighthouse Auth Service.
- This will allow LPB to stop making direct calls in OKTA

2024-05-01 21:48 UTC, jw81 commented on .ruby-version
> +3.2.3
Team BananaPeals [updated the version of ruby baked into the Base Ruby image](https://github.com/department-of-veterans-affairs/health-apis-docker-octopus/pull/201) we utilize.
This requires us to update the ruby version that LPB is targeting.

2024-05-01 21:52 UTC, jw81 commented on Gemfile
> +gem 'jwt', '2.5.0'
The update to the base ruby image mentioned [here](https://github.com/department-of-veterans-affairs/lighthouse-platform-backend/pull/360/files#r1586863879) lead to this.  The version of `jwt` gem we were using wasn't compatible with the version of ruby we were forced to move to.

2024-05-01 21:53 UTC, jw81 commented on app/api/validators/provided_oauth_params.rb
> +      rescue JWT::JWKError
The update to the base ruby image mentioned [here](https://github.com/department-of-veterans-affairs/lighthouse-platform-backend/pull/360/files#r1586863879) lead to this. We had to bump up to a newer version of the `jwt` gem and that new gem version changed what exception is raised.

2024-05-01 21:55 UTC, jw81 commented on app/api/v0/consumers.rb
> +
Once we fully switch over to utilizing Lighthouse Auth Service, this `if..else..end` logic and all `Okta::` scoped logic will be removed.

2024-05-01 21:58 UTC, jw81 commented on app/services/lighthouse_auth/api_client.rb
> +
I will add the following env vars to LPB's deployment unit repo and the AWS ParamStore before this is merged.
```
lighthouse_auth_service
lighthouse_auth_api_key
lighthouse_auth_access_key
```

I will follow up here with an update once I have completed that work.

2024-05-01 21:59 UTC, jw81 commented on build.sh
> +if [ "${RELEASE:-false}" == "true" ]; then
This update was recommended by Team Shanktopus.

2024-05-03 14:51 UTC, gileswells requested changes
Have some feedback but overall this looks very good.

2024-05-03 14:51 UTC, gileswells commented on app/services/lighthouse_auth/app_create/service.rb
> +        existing_auth_ref.discard if existing_auth_ref.present?
I know this is how we're currently doing this but I'm not a fan of this. We're discarding the references and thus making the okta apps orphaned without good cause.

2024-05-03 14:51 UTC, gileswells commented on app/services/lighthouse_auth/app_create/service.rb
> +        auth_ref_key = ConsumerAuthRef::KEYS["sandbox_#{type}_oauth_ref".to_sym]
Obviously right now we are just using this for sandbox only but having the ability to set the environment on this method would be good for the future. I'm ok leaving it as is for now.

2024-05-03 14:51 UTC, gileswells commented on lib/tasks/add_lh_auth_categories.rake
> +}.freeze
Is there a reason for adding a new mapping in the oauth_info field using these values as opposed to pulling from the `sandboxAud` and `productionAud` values? My spot check shows that they line up with the already existing `sandboxAud` property. 

Also, how will this work if we eventually start managing prod access credentials through LPB when we get user accounts spun up?

2024-05-03 14:51 UTC, gileswells commented on lib/tasks/add_lh_auth_categories.rake
> +      oauth_info['ccgInfo']['lighthouse_auth_service_category'] = category
If we still want to list off the lighthouse auth service category as it's own property in the JSON field then I would suggest going camel case so we match the casing of the existing JSON properties.
```suggestion
      oauth_info['acgInfo']['lighthouseAuthServiceCategory'] = category
    when :ccg
      oauth_info['ccgInfo']['lighthouseAuthServiceCategory'] = category
```

2024-05-03 16:00 UTC, jw81 commented on app/services/lighthouse_auth/app_create/service.rb
> +        existing_auth_ref.discard if existing_auth_ref.present?
Yeah, I was reluctant to stray away from what this was currently doing.
I guess, would you rather just leave the pre-existing record alone?
FWIW, that `.discard` is a soft-delete.  So it doesn't actually delete the record.  It just marks it as "discarded".

2024-05-03 16:43 UTC, jw81 commented on app/services/lighthouse_auth/app_create/service.rb
> +        auth_ref_key = ConsumerAuthRef::KEYS["sandbox_#{type}_oauth_ref".to_sym]
If you're good, I'd rather leave it as-is for now.
I just prefer to avoid adding "potential future" things until it's certain it'll be used/needed.

2024-05-03 16:50 UTC, jw81 commented on lib/tasks/add_lh_auth_categories.rake
> +}.freeze
From my discussions with @crolarlibertyva during development on this, I learned that moving forward, Team Pivot will no longer be providing us with the `sandboxAud`/`productionAud` values.  Instead, they'll be providing us the category + auth type values. (ex. `claims` and `claims/system`).  Correct me if I misunderstood anything @crolarlibertyva .

So this rake task should really only need to be ran once to set the new lighthouse auth service category for existing APIs today.  Then going forward, when we add new APIs, we would be making sure to set the lighthouse auth service category attribute instead of the `sandboxAud` and `productionAud` attributes.

2024-05-03 16:56 UTC, jw81 commented on lib/tasks/add_lh_auth_categories.rake
> +      oauth_info['ccgInfo']['lighthouse_auth_service_category'] = category
D'oh 🤦 
My ruby-mind took over there.  😜 
Yeah, that should follow the JS naming convention.  There's a couple places I'll need to update that at.  So I'll go add a commit to change all of them.

2024-05-03 17:00 UTC, crolarlibertyva commented on lib/tasks/add_lh_auth_categories.rake
> +}.freeze
Correct.

2024-05-03 17:21 UTC, jw81 commented on lib/tasks/add_lh_auth_categories.rake
> +      oauth_info['ccgInfo']['lighthouse_auth_service_category'] = category
Made that change [here](https://github.com/department-of-veterans-affairs/lighthouse-platform-backend/pull/360/commits/2b01d7ba7565ccea160f1608e50e3f78c3dfa499). 

(of course the build is failing now due to random Docker rate-limiting 😑)

2024-05-08 14:16 UTC, gileswells commented on app/services/lighthouse_auth/app_create/service.rb
> +        existing_auth_ref.discard if existing_auth_ref.present?
Unfortunately, leaving the pre-existing record alone causes an issue where you cannot update a consumer record through rails_admin (short term problem but annoying all the same). Let's leave it and discuss how we want to address this after we get into the process of user accounts where they might genuinely have multiple client IDs of which they would need access to retrieve/update the credentials of.

2024-05-08 14:18 UTC, gileswells approved these changes

2024-05-08 14:43 UTC, merged